name: CI

on: [push]

jobs:
  build:
    name: Build [${{ matrix.os }}, Node.js v${{ matrix.node }}]
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        node: [
            12.x, # Used by Function Apps
            14.x, # Node.js LTS
            15.x, # Node.js current
          ]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          check-latest: true
      - run: yarn --frozen-lockfile
      - run: yarn build